[general]
log_level="info"
log_format="json"

[backend]
type="mqtt"

[backend.mqtt]
auth="generic"
server="mqtt://mosquitto:1883"
clean_session=true
qos=0
connect_attempts=5
connect_delay="1s"
subscribe_topic="gateway/+/command/+"
publish_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"

[integration]
type="mqtt"

[integration.mqtt]
auth="generic"
server="mqtt://mosquitto:1883"
clean_session=true
qos=0
connect_attempts=5
connect_delay="1s"
topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
